openapi: "3.0.0"
info:
  title: Mirrulations Search API
  version: "1.3.0"
  description: API for searching regulatory documents in the Mirrulations system

paths:
  /search/:
    get:
      summary: Search documents by keyword with optional filters
      parameters:
        - name: str
          in: query
          description: The search term to query against document titles and docket IDs
          required: false
          schema:
            type: string
          example: "Medicare"
        - name: document_type
          in: query
          description: Filter results by document type
          required: false
          schema:
            type: string
          example: "Proposed Rule"
        - name: agency
          in: query
          description: Filter results by agency ID
          required: false
          schema:
            type: string
          example: "CMS"
        - name: cfr_part
          in: query
          description: "Filter results by CFR part. NOTE: Not yet active - pending cfrparts table availability in RDS"
          required: false
          schema:
            type: string
          example: "42 CFR Parts 413 and 512"
      responses:
        "200":
          description: A list of matching documents (max 50 results)
          content:
            application/json:
              schema:
                type: array
                maxItems: 50
                items:
                  type: object
                  properties:
                    docket_id:
                      type: string
                      example: "CMS-2025-0240"
                    title:
                      type: string
                      example: "CY 2026 Changes to the End-Stage Renal Disease..."
                    cfrPart:
                      type: string
                      nullable: true
                      example: null
                    agency_id:
                      type: string
                      example: "CMS"
                    document_type:
                      type: string
                      example: "Proposed Rule"